### PR TITLE
Adds name and getPtr to Meta

### PR DESCRIPTION
**Pull request by iamPHEN**
Gives way to name holders using registerName.

Adds name() function to MetaHolder which returns the registered name of the class.

Interface is a bit icky (have to call two functions), open to suggestions.

### CODE REVIEW

**Comment by EliasD** [comment]
I can agree with registering class name (though you don't have to include <string.h> in Meta.h, remove it and I'll accept this part of PR)

But getPtr is pretty dangerous, because there are situations where you can create Member without passing member pointer to it. And why would you need to get raw pointer to member anyway? People rarely use them and it can make code ugly.
After all, there are Member::get/set functions after all which do all the checking :)

Can you show some cases where you need pointer to member from Member class? Maybe we can come up with some better functions for it.

**Comment by iamPHEN** [comment]
>you don't have to include in Meta.h, 

Oops,  might be leftover from when I was returning a string instead of char*. I'll remove this. 

-
>why would you need to get raw pointer to member anyway?

My use case is for passing to python bindings.  It's convient to expose these ptrs so python can directly read/write to c++ objects. 

Example:
```
py::class<MyClass> pyclass(meta::<MyClass>::getName(), py::init<>) 

meta::doAllMembers([&pyclass] (const auto& m) { def_readwrite(m.getName(), m.getPtr())  });
```

**Comment by EliasD** [comment]
Okay, I see. Well then, you'll need to add function named `hasPtr()` which will return `hasMemberPtr`. If it's false and you still call `m.getPtr()`, it needs to throw std::runtime_error, because there's no way for caller to check if he got correct pointer or not. 
And then I'll accept all your changes :)

Btw, it would be great to have an example of defining `py::class` using MetaStuff lib which will use getter/setter functions to define python properties (instead of just using raw pointers to members)

**Comment by EliasD** [comment]
Ok, I'll merge it and I'll add my proposed changes myself :)

**Pull request merged**
